language: java
jdk:
  - openjdk8

branches:
  only:
    - master
# Travis CI를 어느 브렌치가 푸시될때 수행할지 지정
# 현재 옵션은 오직 master 브랜치에 push될 때만 수행

before_install:
  - chmod +x gradlew

# Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정


script: "./gradlew clean build"
# master 브랜치에 푸시되었을 때 수횅하는 명령어
# 프로젝트 내부에 둔 gradlew을 통해 clean & build를 수행

#CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - z7942s@naver.com
# Travis CI 실행 완료 시 자동으로 알람이 가도록 설정